// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq4J0VZpxMms4g0k_UN97jOpybUu_31oA',
    appId: '1:219936833939:android:7ad65ad95162e5abada866',
    messagingSenderId: '219936833939',
    projectId: 'chatapp-73e53',
    storageBucket: 'chatapp-73e53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcGqPJ-haHA44trZrX2wcDJJNPI6vt6cE',
    appId: '1:219936833939:ios:b1d8d53d629dace3ada866',
    messagingSenderId: '219936833939',
    projectId: 'chatapp-73e53',
    storageBucket: 'chatapp-73e53.appspot.com',
    iosClientId:
        '219936833939-ti12a2o9v0amhcq6hb0t17he4d5atj5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
